### PR TITLE
Add note to README.md about package managers

### PR DESCRIPTION
**Pull request by chausner**
Now that liblsl is available on Conan Center, I suggest to add a note about package managers to the README.md.

### CODE REVIEW

**Comment by cboulay** [comment]
Looks good, thanks!
I'm going to add an issue in sccn/labstreaminglayer and tag you in it about updating the main build docs to add information about how to maintain the vcpk and conan distributions. I don't know where to begin. liblsl 1.16 is out but vcpk is still on 1.14.

**Comment by chausner** [comment]
> liblsl 1.16 is out but vcpk is still on 1.14.

I already submitted an update for the vcpkg port to 0.16.0: https://github.com/microsoft/vcpkg/pull/21284. It has been approved but might take a few days until it's merged.

> I'm going to add an issue in sccn/labstreaminglayer and tag you in it about updating the main build docs to add information about how to maintain the vcpk and conan distributions. I don't know where to begin.

Yes, let me summarize the steps needed to update these ports so that you or somebody else can easily keep them up-do-date in the future.

**Comment by chausner** [comment]
> I already submitted an update for the vcpkg port to 0.16.0: https://github.com/microsoft/vcpkg/pull/21284. It has been approved but might take a few days until it's merged.

It's merged now.

**Comment by chausner** [comment]
@cboulay https://github.com/sccn/labstreaminglayer/pull/97 has been merged. Anything speaking against merging this MR, as well?

**Comment by cboulay** [comment]
I'm sorry, I thought I already merged it. Thanks again!

**Pull request merged**
