### PR TITLE
CMake: add object libraries to the export set for static builds

### LINKED ISSUE #138: CMake install broken for static builds
When setting `LSL_BUILD_STATIC=ON`, the CMake install command fails with:
```
CMake Error: install(EXPORT "LSLTargets" ...) includes target "lsl" which requires target "lslobj" that is not in any export set.
CMake Error: install(EXPORT "LSLTargets" ...) includes target "lsl" which requires target "lslboost" that is not in any export set.
CMake Error in CMakeLists.txt:
  export called with target "lsl" which requires target "lslobj" that is not
  in any export set.


CMake Error in CMakeLists.txt:
  export called with target "lsl" which requires target "lslboost" that is
  not in any export set.
```

Seems commit 730e13050142f7140a8b3de85b2a2b164eb1bc0e broke it.

### PR DESCRIPTION
**Pull request by tstenner**
For shared builds, the linker combines all object files and CMake discards the private properties of the `lslboost` and `lslobj` targets.
For shared libraries, it just combines the object files and adds references to the interface properties of the two object libraries, so they need to be imported.

Copying the properties manually is messy and error-prone, so this PR adds the two object libraries to the export this. Hopefully fixes #138.

### CODE REVIEW

**Comment by tstenner** [comment]
Paging @chausner

**Comment by cboulay** [comment]
Also need to add `-DLSL_BUILD_STATIC=ON` to CI scripts.

**Comment by chausner** [comment]
Yes, this seems to fix the issue, thanks! 👍

**Comment by tstenner** [comment]
> Also need to add `-DLSL_BUILD_STATIC=ON` to CI scripts.

Well, static builds are not something I would want to encourage, but it needs to be tested. Windows has the biggest issues with the whole `dllexport`/`dllimport` and `.dll` / `.lib` shenanigans, so I've added a separate MinGW build in 
4e7d4c8810ef79dade0ee8ae18cd8a80b38e4526. The resulting packages are huge, but it covers MinGW and static builds at once.

**Pull request merged**
