### PR TITLE
Remove old boost subset in external

### PR DESCRIPTION
**Pull request by tstenner**
As previously discussed in length at https://github.com/sccn/labstreaminglayer/issues/227 and at the workshop I made some new latency measurements with the old included boost and the new lslboost based on Boost 1.67:

    Boost     Mean     0%     25%     50%     75%    100%
    lslboost 1,731	0,958	1,021	1,987	2,004	4,039
    external 2,074	1,287	1,986	2,003	2,015	4,044
    (1.57)          1,038   1,986   2.002   2.020   4.060
    (1.58)          0,967   13,20   23.03   27.02   53.81

As the new Boost is slightly faster, produces fewer warnings and is easier to port to the upcoming C++ networking stdlib, I'd therefore propose to remove the old included Boost subset in external and use the new subset in lslboost as standard. We've had it in production at our lab for almost an entire year and I haven't noticed any additional problems so I don't expect any

### CODE REVIEW

**Comment by tstenner** [comment]
Yes, Windows server 2012. I also added the old numbers for Boost 1.57 (before the change was introduced) as 1.58 (right after):

    Boost     Mean     0%     25%     50%     75%    100%
    lslboost 1,731	0,958	1,021	1,987	2,004	4,039
    external 2,074	1,287	1,986	2,003	2,015	4,044
    (1.57)          1,038   1,986   2.002   2.020   4.060
    (1.58)          0,967   13,20   23.03   27.02   53.81

**Comment by mgrivich** [comment]
I'm fine with the merge. Thanks for keeping on top of this and taking data. This will break the old projects files as the underlying boost is moved (xcode, visual studio, code.blocks). I can fix those if you'd rather not dirty your hands with non CMake.

**Comment by tstenner** [comment]
I'd love to, but the only IDEs from the list I have installed are xcode 7.3 and VS2017 so I won't be any help there.
I can, however, update the references in the Android CMakeLists.txt later.

**Comment by tstenner** [comment]
So I tested this some more and I got the string sending example to work with the newest NDK and improved some things along the way: https://github.com/labstreaminglayer/liblsl-Android/pull/2

Could you check if https://github.com/labstreaminglayer/liblsl-Android/pull/1 works for your configuration and we'll tackle https://github.com/labstreaminglayer/liblsl-Android/pull/2 when there's some more time?

**Comment by mgrivich** [comment]
Okay. It might be some weeks till I get to it. I have a deadline with SfN that has to take top priority for now.

**Comment by mgrivich** [comment]
I've starting making changes for the other platforms. I don't think I can edit this pull request because it is in your repository. Would you rather I make branch in sccn/liblsl or that I make a branch in my own repository, which you pull into your repository and then pull into sccn/liblsl?

**Comment by tstenner** [comment]
I've enabled maintainer access, so everyone with write access to sccn/liblsl can push to the branch at tstenner/liblsl, but I've also pushed the branch to sccn/liblsl so you can push to it without adding my repository first.

**Comment by mgrivich** [comment]
I updated the XCode, Visual Studio, and code.blocks projects in the sccn/liblsl remove_old_boost branch. I then merged that branch into master. There were merge conflicts with .appveyor.yml and .travis.yml. I made intelligent guesses on how to resolve these conflicts. Please confirm or fix these files (in master)

**Pull request closed without merging**
